### ISSUE TITLE
Unable to use creatures imported with TTRPG statblocks

### ISSUE THREAD

**Issue by c1phercraft** [javalent/initiative-tracker#35]
Adding the encounter code block yields undefined creatures:

```
\```encounter
name: Example
creatures:
- 3: Goblin
\```
```
(Using back slashes to escape the code block.)

This will show up as "__undefined__ Goblins"  and the initiative tracker will show no creatures at all.

![image](https://user-images.githubusercontent.com/15361495/163220317-3b838f40-f214-4023-9594-377acf061344.png)

I have imported from DndAppFile and 5e.tools, just to see whether it is a format issue. I see 490 homebrew monsters in the settings; they are not listed there though.
The `data.json` file does include the monsters and the JSON format is sound. Adding `statblock` for a Goblin works without a problem.

![image](https://user-images.githubusercontent.com/15361495/163220460-08a825c6-0445-4bd1-ae04-bf66d81b77de.png)

I've updated all plugins and restarted Obsidian, but that did not make a difference. Neither does switching between live preview and preview.

TTRPG statblocks 2.14.2
Initiative Tracker 7.4.1
Obsidian 0.14.2
Dice Roller 8.3.1

_Edit: Added Dice roller version number._

**Comment by c1phercraft** [comment]
Just went into the TTRPG statblocks setting and now... the creatures are listed there. I'm confused.

But, the original issue is still there: encounters don't work. I do see a little white face top-left of Obsidian when I leave an encounter code block and it tries to render it in live-preview. Any logging I found has to do with 3D rendering it seems, so I'm unsure whether that's related or not.

**Comment by c1phercraft** [comment]
Ok, so when I disabled the Dice roller plugin, I saw 3 Goblins appear! The default encounter now works, but the dice (obviously) do not. I hope this helps with the investigation.

Dice Roller 8.3.1

**Comment by TiltedAiri** [comment]
Am just here to say that I'm having the same problem as c1phercraft. Encounter numbers for mobs all show up as undefined with Dice Roller enabled.

If it's 

```encounter
name: Example
creatures:
 - 1d6: Goblin
```

I can get an actual number in there. But if it's

```encounter
name: Example
creatures:
 - 3: Goblin
```
like in the actual example given in the main page it returns Undefined Goblins

**Comment by Chr9sG** [comment]
Have you updated your plugins? This was occurring in earlier iterations of initiative tracker but an update fixed the issue.

**Comment by TiltedAiri** [comment]
Yes I updated them before posting this just to make sure it wasn't that, and checked again now and I'm still having the problem and Obsidian says that all Plugins are up-to-date

**Comment by shunnkou** [comment]
Hello, I'm having the same problem as c1phercraft and TiltedAiri. My plugins are all up-to-date as well.

TTRPG statblocks 2.14.10
Initiative Tracker 7.5.0
Obsidian 0.15.3
Dice Roller 8.6.0

**Comment by SondreElg** [comment]
I've not been able to replicate this issue in the latest version, has this been fixed at some point?

TTRPG statblocks 2.15.1
Initiative Tracker 8.0.6
Obsidian 0.15.9
Dice Roller 8.6.3

**Comment by TiltedAiri** [comment]
Unfortunatly it still does not work for me despite all the past updates in the last few months

TTRPG Statblocks 2.16.2
Initiative Tracker 8.0.7
Obsidian 0.15.9
Dice roller 8.6.3

**Comment by SondreElg** [comment]
I updated all plugins and took a closer look.
It seems like the issue appears if you have the setting "Always render dice" enabled.

TTRPG Statblocks 2.16.2
Initiative Tracker 8.0.7
Obsidian 0.15.9
Dice roller 8.6.3

**Comment by TiltedAiri** [comment]
Yeah that fixed it! Thanks!

**Comment by c1phercraft** [comment]
I can also confirm that disabling _Always render dice_ "fixes" the issue.

**Comment by danstreeter** [comment]
I too can confirm I was having this issue but disabling "Always render dice" within the Dice Roller plugin fixed it.

TTRPG Statblocks 2.16.2
Initiative Tracker 8.0.7
Obsidian 0.15.9
Dice roller 8.6.4

**Comment by SondreElg** [comment]
The "Always render dice" setting of the Dice Roller plugin seem to work nicely with Initiative Tracker now.
